### ISSUE TITLE
Incorrect FAIL assessment for DM34 - SPN 4129 and SPN 4132 (Part 1 Test 26 and Part 2 Test 17)

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#1001] opened 2021-05-12 20:55 UTC
Bug found with tool version: v 3.0.9

Failing for reporting "NOT AVAILABLE" in Part 1 Test 26 and Part 2 Test 17 is not acceptable.

SPN 4129:
![2021-05-12 13_47_54-Window](https://user-images.githubusercontent.com/46825003/118043768-a8632400-b32a-11eb-8cee-91065b4ac8b2.jpg)

SPN 4132:
![2021-05-12 13_49_38-Window](https://user-images.githubusercontent.com/46825003/118043800-b1ec8c00-b32a-11eb-941b-b756af29db2e.jpg)

12:36:51.7120 DS Request for PGN 40960 to Engine #1 (0) for SPNs 4127, 4128, 4129, 4130, 4131, 4132
12:36:51.7150 18EA00F9 [3] 00 A0 00 (TX)
12:36:51.7206 18A0F900 [8] 0F 0F FF FF FF FF FF FF
DM34 NTE Status from Engine #1 (0):  {
                          NOx NTE Control Area Status = Outside Area (0)
  Manufacturer-specific NOx NTE Carve-out Area Status = Outside Area (0)
                       NOx NTE Deficiency Area Status = Not available (3)
                           PM NTE Control Area Status = Outside Area (0)
   Manufacturer-specific PM NTE Carve-out Area Status = Outside Area (0)
                        PM NTE Deficiency Area Status = Not available (3)
}

PGN 40960 with Supported SPNs 4127, 4128, 4129, 4130, 4131, 4132
12:36:51.7206 18A0F900 [8] 0F 0F FF FF FF FF FF FF
Found: DM34 NTE Status from Engine #1 (0):  {
                          NOx NTE Control Area Status = Outside Area (0)
  Manufacturer-specific NOx NTE Carve-out Area Status = Outside Area (0)
                       NOx NTE Deficiency Area Status = Not available (3)
                           PM NTE Control Area Status = Outside Area (0)
   Manufacturer-specific PM NTE Carve-out Area Status = Outside Area (0)
                        PM NTE Deficiency Area Status = Not available (3)
}

FAIL: 6.1.26.6.a - SPN 4129 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 4132 was received as NOT AVAILABLE from Engine #1 (0)

12:38:51.5897 DS Request for PGN 40960 to Engine #1 (0) for SPNs 4127, 4128, 4129, 4130, 4131, 4132
12:38:51.5938 18EA00F9 [3] 00 A0 00 (TX)
12:38:51.5962 18A0F900 [8] 0F 0F FF FF FF FF FF FF
DM34 NTE Status from Engine #1 (0):  {
                          NOx NTE Control Area Status = Outside Area (0)
  Manufacturer-specific NOx NTE Carve-out Area Status = Outside Area (0)
                       NOx NTE Deficiency Area Status = Not available (3)
                           PM NTE Control Area Status = Outside Area (0)
   Manufacturer-specific PM NTE Carve-out Area Status = Outside Area (0)
                        PM NTE Deficiency Area Status = Not available (3)
}

PGN 40960 with Supported SPNs 4127, 4128, 4129, 4130, 4131, 4132
12:38:51.5962 18A0F900 [8] 0F 0F FF FF FF FF FF FF
Found: DM34 NTE Status from Engine #1 (0):  {
                          NOx NTE Control Area Status = Outside Area (0)
  Manufacturer-specific NOx NTE Carve-out Area Status = Outside Area (0)
                       NOx NTE Deficiency Area Status = Not available (3)
                           PM NTE Control Area Status = Outside Area (0)
   Manufacturer-specific PM NTE Carve-out Area Status = Outside Area (0)
                        PM NTE Deficiency Area Status = Not available (3)
}

FAIL: 6.2.17.6.a - SPN 4129 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 4132 was received as NOT AVAILABLE from Engine #1 (0)

In Part 2 Test 16 of the test, the below response is accepted with no issues. 
Start Test 2.16 - DM34: NTE status

12:38:30.7023 Global DM34 Request
12:38:30.7051 18EAFFF9 [3] 00 A0 00 (TX)
12:38:30.7066 18A0FF00 [8] 0F 0F FF FF FF FF FF FF
DM34 NTE Status from Engine #1 (0):  {
                          NOx NTE Control Area Status = Outside Area (0)
  Manufacturer-specific NOx NTE Carve-out Area Status = Outside Area (0)
                       NOx NTE Deficiency Area Status = Not available (3)
                           PM NTE Control Area Status = Outside Area (0)
   Manufacturer-specific PM NTE Carve-out Area Status = Outside Area (0)
                        PM NTE Deficiency Area Status = Not available (3)
}

J1939-84 spec screen shot for Part2 Test 16,
![2021-05-12 13_54_21-Window](https://user-images.githubusercontent.com/46825003/118043947-e2ccc100-b32a-11eb-85b6-5cead1dde381.jpg)

**Comment by vmuthu2** [comment] 2021-05-12 21:11
![SPN4132](https://user-images.githubusercontent.com/46825003/118044741-e57be600-b32b-11eb-8e43-03af2886a9d8.jpg)
![J1939-84_Spec](https://user-images.githubusercontent.com/46825003/118044742-e6147c80-b32b-11eb-9130-3e6e4062bb06.jpg)
![SPN4129](https://user-images.githubusercontent.com/46825003/118044744-e6147c80-b32b-11eb-817e-debc78c74d11.jpg)

**Comment by gumbelmj** [comment] 2021-05-13 01:57
@vmuthu2, this is not a bug.  The tool is following the specification.

In Part 1 Test 26, the tool is requesting SPs which Engine #1 claims to support:
```
12:36:51.7120 DS Request for PGN 40960 to Engine #1 (0) for SPNs 4127, 4128, 4129, 4130, 4131, 4132
```

However, Engine #1 returns N/A for SPs is claims to support in the Data Stream:
```
12:36:51.7150 18EA00F9 [3] 00 A0 00 (TX)
12:36:51.7206 18A0F900 [8] 0F 0F FF FF FF FF FF FF
DM34 NTE Status from Engine #1 (0): {
NOx NTE Control Area Status = Outside Area (0)
Manufacturer-specific NOx NTE Carve-out Area Status = Outside Area (0)
NOx NTE Deficiency Area Status = Not available (3)
PM NTE Control Area Status = Outside Area (0)
Manufacturer-specific PM NTE Carve-out Area Status = Outside Area (0)
PM NTE Deficiency Area Status = Not available (3)
}
```

Therefore this is a failure. From the specification:
>6.2.17.6.a. Fail if no response/no valid data for any upon request SPN indicated as supported in DM24, per Table A-1.

Since N/A is not valid data for supported SPs, a failure is reported.  The same logic applies for Part 2 Test 17.

In Part 2 Test 16, since the module is allowed to send N/A without failure, there is no failure reported.

The bug is with the ECM reporting that SP 4129 and 4132 are supported then returning N/A in the data stream.

**Comment by ericthomasswenson** [comment] 2021-05-13 04:25
In Part 2, there is a strategy to accept part 1 values for many queries without detailed evaluation to minimize duplicated failure messages.

In general, SPs that are not supported should not appear in DM24, we made an exception for 976.  

Not sure it makes sense to add an exception for Deficiency Area Status.  

If there are no deficiency areas, 11b is reasonable (as stated in J1939-84).
To me, 00b (outside area) suggests that 01b (Inside area) is capable of being sent.  

Better policy to me is to calibrate the DM24 data stream support bits to 1 (not Supported) for SP 4129 and 4132. Or omit them altogether from DM24, as discussed in J1939-73 5.7.24.1 below.

**Comment by ericthomasswenson** [comment] 2021-05-13 04:50
From SAE J1939-73

5.7.24.1 SPN Supported This parameter defines each SPN that is supported by the ECU in data stream, expanded freeze frame, scaled test results, or rationality fault SPN data. **_Any SPN not supported for at least one of these purposes will not be transmitted in this parameter group_**. The SPNs reported may be limited to those required to satisfy regulated OBD requirements. Be aware that some of these supported data stream SPNs may come from different source addresses than the device reporting the DM24 response. Additionally, the SPNs that shall be in DM24 are those identified in SAE J1939DA, excluding those specified in SAE J1939-73. An exception to this rule is if the SPN is in SAE J1939-73 and must be provided as part of an OBD freeze frame, then it must be contained in DM24 (e.g., time since engine start) and can indicate data stream, freeze frame, and test results, if appropriate.    

 Manufacturers may populate the SPN support with a superset list of SPNs for multiple product lines. **_An individual product may have some SPNs in the SPN list reported with the SPN support type as all ones (meaning not supported)._** 
 ...
NOTE: See Table 1 for the conventions to be used for NOx Binning and GHG Tracking SPs. These PG for NOx Binning and GHG Tracking are divided into four groups and only 1 SP per group shall be displayed in the DM24 Response. GHG technology tracking (68) and GHG Tracking Hybrid Messages (row 69) groups shall be omitted when they are not supported by the responding device.

**Comment by ericthomasswenson** [comment] 2021-05-13 04:59
I believe there is now sufficient rationale to close this issue.

**Closed as completed by ericthomasswenson** 2021-05-13 04:59 UTC
Labels: bug, invalid, User
