### ISSUE TITLE
113 C is a warm oil temp but not implausible for a sump oil temp

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1250] opened 2023-06-10 16:35 UTC
113 C is a warm oil temp but not implausible for a sump oil temp

Check Table A-1 assumptions for oil water exchanger oil outlet temp v. Sump temp.

PGN 65262 with Supported SPNs 110, 174, 175
13:07:31.4294 18FEEE00 [8] [87 59 55 30](tel:87 59 55 30) FF FF 3C FF
Found: Engine Temperature 1 from Engine #1 (0): 
  SPN   110, Engine Coolant Temperature: 95.000 °C
  SPN   174, Engine Fuel 1 Temperature 1: 49.000 °C
  SPN   175, Engine Oil Temperature 1: 113.656 °C
  SPN   176, Engine Turbocharger 1 Oil Temperature: Not Available
  SPN    52, Engine Intercooler Temperature: 20.000 °C
  SPN  1134, Engine Charge Air Cooler Thermostat Opening: Not Available

WARN: 6.2.17.3.c - N.8 Engine #1 (0) reported value for SPN 175 (113.65625) is implausible

**Comment by ericthomasswenson** [comment] 2023-06-10 16:39
@naroner, is this value sump (exchanger inlet) or (more traditionally oil water exchanger outlet)

**Comment by naroner** [comment] 2023-06-15 19:56
@ericthomasswenson This was caused by a HiL model issue, I haven't seen this issue on a actual vehicle. 

I would propose to close this issue since it isn't a tool issue.

**Comment by ericthomasswenson** [comment] 2023-06-16 10:20
Thanks for the explanation Nathan

**Closed as completed** 2023-06-16 10:20 UTC
