### ISSUE TITLE
Multiple CAL-ID/CVNs in a single DM19

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#966] opened 2021-04-29 23:14 UTC
WARN: 6.1.7.3.b - Engine #1 (0) provided more than one CAL ID and CVN pair in a single DM19 message

Specification issue

Most engine manufacturers report multiple CAL-Ids and CVNs in a single DM19. Why cannot this be changed to an INFO?

**Comment by gumbelmj** [comment] 2021-04-30 01:06
This appears to be a duplicate of #811

**Comment by ericthomasswenson** [comment] 2021-04-30 06:07
And #813

Proposed text is documented in #811

**Comment by battjt** [comment] 2021-04-30 13:06
Duplicate of #813 and #811.

**Closed as completed by battjt** 2021-04-30 13:06 UTC
Labels: documentation, duplicate, enhancement
