### ISSUE TITLE
DM28 Handling in Part 11 Incorrect

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1132] opened 2022-04-28 18:26 UTC
SA 61 accused for premature permanent fault erasure when starting with no permanent fault.

SA 39 response may have gotten in the way

**Comment by ericthomasswenson** [comment] 2022-08-23 20:30
Not observed on 3.1.4 with a monolithic Engine OBD ECU.
Need review with distributed architecture.

**Comment by battjt** [comment] 2022-10-04 19:51
Wating for confirmation that it's still a bug.

**Comment by battjt** [comment] 2022-10-23 16:24
Marked dev complete as duplicate of #1089 .

**Closed as completed** 2024-05-17 17:30 UTC
Labels: bug, User, Latent, brl
