### ISSUE TITLE
New bug or signed time stamp example?

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#882] opened 2021-03-24 02:11 UTC
Start Test 8.14 - DM7/DM30: Command non-continuously monitored test/scaled test results

14:44:44.9995 Sending DM7 for DM30 to Engine #1 (0) for SPN 110
13:33:10.0458 18E300F9 [8] FA 6E 00 10 FF FF FF FF (TX)
14:44:45.0105 18A4F900 [12] FA 6E 00 10 44 00 70 26 80 30 FF FF
DM30 from 0: SPN 110 FMI 16 (SLOT 68) Result: Test Passed. Min: N/A, Value: 34.5, Max: 115 °C
// 13:33:10.0458 is presumed to be a signed time stamp example?

Seems to appear on each query.
Start Test 8.7 - DM28: Permanent DTCs

14:44:09.3632 Global DM28 Request
13:32:34.4121 18EAFFF9 [3] 80 FD 00 (TX)
13:32:34.4147 18FD8000 [8] 40 FF 66 00 04 01 FF FF
DM28 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

14:44:09.9706 Destination Specific DM28 Request to Engine #1 (0)
13:32:35.0221 18EA00F9 [3] 80 FD 00 (TX)
13:32:35.0250 18FD8000 [8] 40 FF 66 00 04 01 FF FF
DM28 from Engine #1 (0): MIL: on, RSL: off, AWL: off, PL: off
DTC 102:4 - Engine Intake Manifold #1 Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

**Comment by gumbelmj** [comment] 2021-03-24 02:15
Yes.  This is another example which was fixed by #830.  Closing as a duplicate of #830

**Closed as completed by gumbelmj** 2021-03-24 02:15 UTC
Labels: duplicate, question
