### ISSUE TITLE
Tool Issues Failure for GHG Tracking when Active/Stored Labels Don't Match Lifetime

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1216] opened 2023-01-06 16:13 UTC
**Tool issues a failure for the labels for active/stored not being a subset of lifetime. This doesn't align with ARB's requirements. I suggest that it is changed to check if stored/lifetime are a subset of active.** 
```
16:45:00.5481 GHG Tracking Arrays from Engine #2 (1)
|-------------------------+-------------+-------------+-------------|
|                         |    Active   |    Stored   |             |
|                         |   100 Hour  |   100 Hour  |   Lifetime  |
|-------------------------+-------------+-------------+-------------|
| Engine Run Time, s      |           0 |         N/A |          17 |
| Vehicle Dist., km       |           0 |           0 |           0 |
| Vehicle Fuel, l         |           0 |           0 |           1 |
| Engine Fuel, l          |           0 |           0 |           2 |
| Eng.Out.Energy, kW-hr   |           0 |           0 |           0 |
| PKE Numerator           |           0 |           0 |           0 |
| Urban Speed Run Time, s |           0 |           0 |           0 |
| Idle Run Time, s        |           0 |           0 |         N/A |
| Engine Idle Fuel, l     |           0 |           0 |           0 |
| PTO Run Time, s         |           0 |           0 |           0 |
| PTO Fuel Consumption, l |           0 |           0 |           0 |
| AES Shutdown Count      |           0 |           0 |         N/A |
| Stop-Start Run Time, s  |           0 |           0 |         N/A |
|-------------------------+-------------+-------------+-------------|

16:45:00.5551 Destination Specific GHGTTL Request to Engine #2 (1)
16:45:00.5571 18EA01F9 [3] 01 FB 00 (TX)
16:45:00.6451 1CFB0101 [28] FA 01 00 00 00 00 00 00 00 F9 00 00 00 00 00 00 00 00 F8 C4 02 00 00 00 00 00 00 00
Green House Gas Lifetime Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 1.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 m
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 708.000 s, Vehicle Distance = 0.000 m

16:45:00.6536 Destination Specific GHGTTA Request to Engine #2 (1)
16:45:00.6556 18EA01F9 [3] 00 FB 00 (TX)
16:45:00.7251 1CFB0001 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Active 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

16:45:00.7261 Destination Specific GHGTTS Request to Engine #2 (1)
16:45:00.7286 18EA01F9 [3] FF FA 00 (TX)
16:45:00.8051 1CFAFF01 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

16:45:00.8066 GHG Active Technology Arrays from Engine #2 (1)
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
|                                     |    Active   |    Active   |    Stored   |    Stored   |             |             |
| Index                               |   100 Hour  |   100 Hour  |   100 Hour  |   100 Hour  |   Lifetime  |   Lifetime  |
| Description                         |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
| SAE/ISO Reserved                    |         N/A |         N/A |         N/A |         N/A |  69,625,446 |           0 |
| Cylinder Deactivation               |         N/A |         N/A |         N/A |         N/A |           0 |           0 |
| Mfg Defined Active Technology 3     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 2     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 1     |           0 |           0 |           0 |           0 |           0 |           0 |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|

FAIL: 6.1.26.18.g - Active 100 hr array value received was greater than zero from Engine #2 (1) for SPN SPN 12694, GHG Tracking Active 100 Hour Active Technology Index: Mfg Defined Active Technology 1
FAIL: 6.1.26.18.f - Active labels received is not an equivalent set of lifetime labels
FAIL: 6.1.26.18.f - Stored labels received is not an equivalent set of lifetime labels
```

**Comment by ericthomasswenson** [comment] 2023-01-06 18:29
There are similar complaints … this may be a duplicate of one of them.

Excess categories not shown, in v 3.1.10.

**Comment by battjt** [comment] 2023-01-13 20:17
Set of labels matching bugs in progress.  Excess categories complete.  Steps 1.26, 2.17 and 11.9 are all being addressed.

**Comment by ericthomasswenson** [comment] 2023-01-20 18:58
Users will recheck with 3.1.13

**Comment by naroner** [comment] 2023-03-31 14:07
@ericthomasswenson This is still an issue in 3.1.19:
```
15:24:27.7941 Destination Specific GHGTTS Request to Engine #2 (1)
15:24:27.7981 18EA01F9 [3] FF FA 00 (TX)
15:24:27.8721 1CFAFF01 [16] FA 00 00 00 00 F9 00 00 00 00 F8 00 00 00 00 00
Green House Gas Stored 100 Hour Active Technology Tracking from Engine #2 (1): 
  Active Technology:  Mfg Defined Active Technology 1 (250), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 2 (249), Time = 0.000 s, Vehicle Distance = 0.000 km
  Active Technology:  Mfg Defined Active Technology 3 (248), Time = 0.000 s, Vehicle Distance = 0.000 km

15:24:27.8751 GHG Active Technology Arrays from Engine #2 (1)
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
|                                     |    Active   |    Active   |    Stored   |    Stored   |             |             |
| Index                               |   100 Hour  |   100 Hour  |   100 Hour  |   100 Hour  |   Lifetime  |   Lifetime  |
| Description                         |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
| SAE/ISO Reserved                    |         N/A |         N/A |         N/A |         N/A |  69,625,446 |           0 |
| Waste Heat Recovery                 |         N/A |         N/A |         N/A |         N/A |           0 |           0 |
| Mfg Defined Active Technology 3     |           5 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 2     |           0 |           0 |           0 |           0 |         N/A |         N/A |
| Mfg Defined Active Technology 1     |           0 |           0 |           0 |           0 |           0 |           0 |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|

FAIL: 6.11.13.12.e - Number of active labels received differs from the number of lifetime labels
FAIL: 6.11.13.12.e - Number of stored labels received differs from the number of lifetime labels
FAIL: 6.11.13.12.f - Active labels received is not a subset of lifetime labels
FAIL: 6.11.13.12.f - Stored labels received is not a subset of lifetime labels
```

**Comment by naroner** [comment] 2023-03-31 17:40
@ericthomasswenson The above makes more sense to be under #1233

**Comment by battjt** [comment] 2023-04-01 23:01
Using data from this bug report I created a unit test and found the bug.  I assume the correct output should be:
```
10:15:30.0000 GHG Active Technology Arrays from Engine #1 (0)
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
|                                     |    Active   |    Active   |    Stored   |    Stored   |             |             |
| Index                               |   100 Hour  |   100 Hour  |   100 Hour  |   100 Hour  |   Lifetime  |   Lifetime  |
| Description                         |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |    Time, m  |   Dist, km  |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
| Mfg Defined Active Technology 3     |           0 |           0 |           0 |           0 |          12 |           0 |
| Mfg Defined Active Technology 2     |           0 |           0 |           0 |           0 |           0 |           0 |
| Mfg Defined Active Technology 1     |           0 |           0 |           0 |           0 |           0 |           0 |
|-------------------------------------+-------------+-------------+-------------+-------------+-------------+-------------|
```
The bug was a continuation of the "interpreting the lifetime packet as a 100 hour packet" bug that was discovered a while back.

**Closed as completed** 2024-05-17 17:29 UTC
Labels: bug, User, Task 5, brl
